//http://localhost:4000/upload
### POST request to upload file
POST http://localhost:4000/upload
Content-Type: multipart/form-data

--boundary123
Content-Disposition: form-data; name="file"; filename="path_to_your_file.txt"
Content-Type: text/plain

< ./path_to_your_file.txt
--boundary123--